{ ... }: {
  # Generic laptop host — use as the install target on any Intel/AMD laptop.
  # Hardware-configuration.nix is regenerated by `nixos-anywhere
  # --generate-hardware-config` during the fresh install, so the placeholder
  # in this directory is intentionally bare.
  imports = [
    ../../modules/profiles/laptop.nix
  ];

  networking.hostName = "laptop";
}
