{ ... }: {
  # Generic desktop host — use as the install target on any desktop tower.
  # Hardware-configuration.nix is regenerated by `nixos-anywhere
  # --generate-hardware-config` during the fresh install.
  imports = [
    ../../modules/profiles/desktop.nix
  ];

  networking.hostName = "desktop";
}
