# PLACEHOLDER hardware-configuration.nix
# Overwritten by install.sh during nixos-install with the real values
# generated by `nixos-generate-config --show-hardware-config`.
#
# This file exists in the repo as a placeholder so `nix flake check` and
# eval-everywhere work. Don't try to build/activate this on real hardware
# without running install.sh first — the placeholder devices won't exist.

{ lib, modulesPath, ... }: {
  boot.initrd.availableKernelModules = lib.mkDefault [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = lib.mkDefault [ ];
  boot.kernelModules = lib.mkDefault [ "kvm-amd" ];
  boot.extraModulePackages = lib.mkDefault [ ];

  # PLACEHOLDER device paths — install.sh writes real UUIDs here.
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/PLACEHOLDER";
    fsType = "btrfs";
  };
  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-label/PLACEHOLDER-BOOT";
    fsType = "vfat";
  };

  swapDevices = lib.mkDefault [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault true;
}
